CREATE DATABASE IF NOT EXISTS RPGCLOUD2;

CREATE TABLE PLAYER ( ID INT AUTO_INCREMENT, LOGIN VARCHAR(255), PASSWORD VARCHAR(800), EMAIL VARCHAR(255), PRIMARY KEY(ID) );
CREATE TABLE QUEST( ) 
CREATE TABLE TEST( ID INT AUTO_INCREMENT, NAME VARCHAR(255), GOAL VARCHAR(10), RESULT INT, TEST INT, PRIMARY KEY(ID) ) 
CREATE TABLE ADVENTURE( ID INT AUTO_INCREMENT, NAME VARCHAR(255), PRIMARY KEY(ID) ) 
CREATE TABLE HERO( ID INT AUTO_INCREMENT, NAME VARCHAR(255), RACE VARCHAR(255), HP INT, MP INT, ATK INT, DEFENSE INT, AGILITY INT, INTELIGENCE INT, ID_PLAYER INT, ID_WORLD INT, PRIMARY KEY(ID), FOREIGN KEY (ID_PLAYER) REFERENCES PLAYER(ID) );
CREATE TABLE RACE( ID INT AUTO_INCREMENT, NAME VARCHAR(255), HP INT, MP INT, ATK INT, DEFENSE INT, AGILITY INT, INTELIGENCE INT, ID_WORLD INT, PRIMARY KEY(ID) );
CREATE TABLE BATTLE( ID INT AUTO_INCREMENT, ID_HERO_ONE INT, ID_HERO_TWO INT, HP_HERO_ONE INT, HP_HERO_TWO INT, STATUS_BATTLE VARCHAR(10), WIN_BATTLE INT, PRIMARY KEY(ID), FOREIGN KEY (ID_HERO_ONE) REFERENCES HERO(ID) )
 CREATE TABLE PHASE( ID INT AUTO_INCREMENT, ID_HERO_ONE INT, ID_BATTLE INT, DESCRIPTION VARCHAR(400), PRIMARY KEY(ID) ) 
 CREATE TABLE WORLD( ID INT AUTO_INCREMENT, NAME VARCHAR(200), DESCRIPTION VARCHAR(600), PRIMARY KEY(ID) )